In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import warnings
import missingno as msno
warnings.filterwarnings('ignore')
%matplotlib inline

In [14]:
input_file_path = '/Users/gauridhumal/Development Projects/UOL-PROJECTs/CRS/DS/crs_ds/data/raw/MovieSummaries'
output_file_path = '/Users/gauridhumal/Development Projects/UOL-PROJECTs/CRS/DS/crs_ds/data/processed/MovieSummaries'

In [33]:
def read_file(file_name):
    return pd.read_csv(open(f"{input_file_path}/{file_name}", 'r'),delimiter='\t',header=None)

In [16]:
def write_file(df,file_name):
    return df.to_csv(f"{output_file_path}/{file_name}", index=False)

In [34]:
df_movie = read_file('movie.metadata.tsv')

In [35]:
df_movie.head()

,0,1,2,3,4,5,6,7,8
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/01jfsb"": ""Thriller"", ""/m/06n90"": ""Science..."
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey ...,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/02n4kr"": ""Mystery"", ""/m/03bxz7"": ""Biograp..."
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""D..."
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/01jfsb"": ""Thriller"", ""/m/0glj9q"": ""Erotic..."
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}","{""/m/07s9rl0"": ""Drama""}"

In [36]:
df_movie.columns=['m_wikipedia_id','m_freebase_id','m_title','m_release_date','m_box_off_revenue','m_runtime','m_languages','m_countries','m_genres']

In [37]:
df_movie.head()

,m_wikipedia_id,m_freebase_id,m_title,m_release_date,m_box_off_revenue,m_runtime,m_languages,m_countries,m_genres
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/01jfsb"": ""Thriller"", ""/m/06n90"": ""Science..."
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey ...,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/02n4kr"": ""Mystery"", ""/m/03bxz7"": ""Biograp..."
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""D..."
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/01jfsb"": ""Thriller"", ""/m/0glj9q"": ""Erotic..."
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}","{""/m/07s9rl0"": ""Drama""}"

In [38]:
df_movie.shape

(81741, 9)

## Process Movie Summaries

In [91]:
df_movie_summaries = read_file('plot_summaries.txt')

In [92]:
df_movie_summaries.columns=['m_wikipedia_id','m_plot_summary']

In [93]:
df_movie_summaries.head(20)

    m_wikipedia_id                                     m_plot_summary
0         23890098  Shlykov, a hard-working taxi driver and Lyosha...
1         31186339  The nation of Panem consists of a wealthy Capi...
2         20663735  Poovalli Induchoodan  is sentenced for six yea...
3          2231378  The Lemon Drop Kid , a New York City swindler,...
4           595909  Seventh-day Adventist Church pastor Michael Ch...
5          5272176  The president is on his way to give a speech. ...
6          1952976  {{plot}} The film opens in 1974, as a young gi...
7         24225279  The story begins with Hannah, a young Jewish t...
8          2462689  Infuriated at being told to write one final co...
9         20532852  A line of people  drool at the window of the s...
10        15401493  Lola  attempts to gain her father's trust fund...
11        18188932  Milan and Goran are two criminals who smuggle ...
12         2940516  Bumbling pirate crewman  kills his captain aft...
13         1335380  The film is based on the events that happened ...
14         1480747  {{plot}} Following the sudden death of Kid's f...
15        24448645  Despite Lucy's reservations, she agrees to her...
16        15072401  Alan Colby, heir to a vast fortune, reappears ...
17         4018288  Debbie's favorite band is Dream Street, and he...
18         4596602  Ashes to Ashes is set in London, England. The ...
19        15224586  The film follows the experience of Vietnamese ...

In [94]:
df_movie_summaries.shape

(42303, 2)

In [95]:
# Check if the any of the summaries are null
df_movie_summaries[df_movie_summaries['m_plot_summary'].isnull()]

Empty DataFrame
Columns: [m_wikipedia_id, m_plot_summary]
Index: []

In [96]:
# Check if there are any duplicates
df_movie_summaries[df_movie_summaries['m_wikipedia_id'].duplicated()]

Empty DataFrame
Columns: [m_wikipedia_id, m_plot_summary]
Index: []

In [97]:
# Remove {{plot}}
df_movie_summaries['cleaned_m_plot_summary'] = df_movie_summaries['m_plot_summary'].str.replace(r'\{{plot}}', '', regex=True)

In [98]:
df_movie_summaries.head(20)

,m_wikipedia_id,m_plot_summary,cleaned_m_plot_summary
0,23890098,"Shlykov, a hard-working taxi driver and Lyosha...","Shlykov, a hard-working taxi driver and Lyosha..."
1,31186339,The nation of Panem consists of a wealthy Capi...,The nation of Panem consists of a wealthy Capi...
2,20663735,Poovalli Induchoodan is sentenced for six yea...,Poovalli Induchoodan is sentenced for six yea...
3,2231378,"The Lemon Drop Kid , a New York City swindler,...","The Lemon Drop Kid , a New York City swindler,..."
4,595909,Seventh-day Adventist Church pastor Michael Ch...,Seventh-day Adventist Church pastor Michael Ch...
5,5272176,The president is on his way to give a speech. ...,The president is on his way to give a speech. ...
6,1952976,"{{plot}} The film opens in 1974, as a young gi...","The film opens in 1974, as a young girl, Dahl..."
7,24225279,"The story begins with Hannah, a young Jewish t...","The story begins with Hannah, a young Jewish t..."
8,2462689,Infuriated at being told to write one final co...,Infuriated at being told to write one final co...
9,20532852,A line of people drool at the window of the s...,A line of people drool at the window of the s...
10,15401493,Lola attempts to gain her father's trust fund...,Lola attempts to gain her father's trust fund...
11,18188932,Milan and Goran are two criminals who smuggle ...,Milan and Goran are two criminals who smuggle ...
12,2940516,Bumbling pirate crewman kills his captain aft...,Bumbling pirate crewman kills his captain aft...
13,1335380,The film is based on the events that happened ...,The film is based on the events that happened ...
14,1480747,{{plot}} Following the sudden death of Kid's f...,"Following the sudden death of Kid's father ""P..."
15,24448645,"Despite Lucy's reservations, she agrees to her...","Despite Lucy's reservations, she agrees to her..."
16,15072401,"Alan Colby, heir to a vast fortune, reappears ...","Alan Colby, heir to a vast fortune, reappears ..."
17,4018288,"Debbie's favorite band is Dream Street, and he...","Debbie's favorite band is Dream Street, and he..."
18,4596602,"Ashes to Ashes is set in London, England. The ...","Ashes to Ashes is set in London, England. The ..."
19,15224586,The film follows the experience of Vietnamese ...,The film follows the experience of Vietnamese ...

In [99]:
df_movie_summaries['cleaned_m_plot_summary'].str.len()

0         178
1        4559
2        3099
3        4917
4        2425
         ...
42298     220
42299    2971
42300     871
42301    1289
42302    3489
Name: cleaned_m_plot_summary, Length: 42303, dtype: int64

In [100]:
df_movie_summaries['cleaned_m_plot_summary'] = df_movie_summaries['cleaned_m_plot_summary'].str.strip()

In [101]:
df_movie_summaries.head(20)

,m_wikipedia_id,m_plot_summary,cleaned_m_plot_summary
0,23890098,"Shlykov, a hard-working taxi driver and Lyosha...","Shlykov, a hard-working taxi driver and Lyosha..."
1,31186339,The nation of Panem consists of a wealthy Capi...,The nation of Panem consists of a wealthy Capi...
2,20663735,Poovalli Induchoodan is sentenced for six yea...,Poovalli Induchoodan is sentenced for six yea...
3,2231378,"The Lemon Drop Kid , a New York City swindler,...","The Lemon Drop Kid , a New York City swindler,..."
4,595909,Seventh-day Adventist Church pastor Michael Ch...,Seventh-day Adventist Church pastor Michael Ch...
5,5272176,The president is on his way to give a speech. ...,The president is on his way to give a speech. ...
6,1952976,"{{plot}} The film opens in 1974, as a young gi...","The film opens in 1974, as a young girl, Dahli..."
7,24225279,"The story begins with Hannah, a young Jewish t...","The story begins with Hannah, a young Jewish t..."
8,2462689,Infuriated at being told to write one final co...,Infuriated at being told to write one final co...
9,20532852,A line of people drool at the window of the s...,A line of people drool at the window of the s...
10,15401493,Lola attempts to gain her father's trust fund...,Lola attempts to gain her father's trust fund...
11,18188932,Milan and Goran are two criminals who smuggle ...,Milan and Goran are two criminals who smuggle ...
12,2940516,Bumbling pirate crewman kills his captain aft...,Bumbling pirate crewman kills his captain aft...
13,1335380,The film is based on the events that happened ...,The film is based on the events that happened ...
14,1480747,{{plot}} Following the sudden death of Kid's f...,"Following the sudden death of Kid's father ""Po..."
15,24448645,"Despite Lucy's reservations, she agrees to her...","Despite Lucy's reservations, she agrees to her..."
16,15072401,"Alan Colby, heir to a vast fortune, reappears ...","Alan Colby, heir to a vast fortune, reappears ..."
17,4018288,"Debbie's favorite band is Dream Street, and he...","Debbie's favorite band is Dream Street, and he..."
18,4596602,"Ashes to Ashes is set in London, England. The ...","Ashes to Ashes is set in London, England. The ..."
19,15224586,The film follows the experience of Vietnamese ...,The film follows the experience of Vietnamese ...

In [102]:
#To confirm that the whitespaces have indeed been stripped
df_movie_summaries['cleaned_m_plot_summary'].str.len()

0         178
1        4559
2        3099
3        4917
4        2425
         ...
42298     220
42299    2971
42300     871
42301    1289
42302    3489
Name: cleaned_m_plot_summary, Length: 42303, dtype: int64

## Combine Movie and Movie summary

In [131]:
# Join the top trending movies wiht the movie basics to get other details.

df_movies_combined = df_movie_summaries.set_index('m_wikipedia_id').join(df_movie.set_index('m_wikipedia_id'),on="m_wikipedia_id",lsuffix='_summary', rsuffix='_movie')

In [140]:
df_movies_combined.head()

,m_plot_summary,cleaned_m_plot_summary,m_freebase_id,m_title,m_release_date,m_box_off_revenue,m_runtime,m_languages,m_countries,m_genres
m_wikipedia_id,,,,,,,,,,
23890098,"Shlykov, a hard-working taxi driver and Lyosha...","Shlykov, a hard-working taxi driver and Lyosha...",/m/076w2lb,Taxi Blues,1990-09-07,NaN,110.0,"{""/m/06b_j"": ""Russian Language""}","{""/m/0f8l9c"": ""France"", ""/m/05vz3zq"": ""Soviet ...","{""/m/07s9rl0"": ""Drama"", ""/m/03q4nz"": ""World ci..."
31186339,The nation of Panem consists of a wealthy Capi...,The nation of Panem consists of a wealthy Capi...,/m/0gkz15s,The Hunger Games,2012-03-12,686533290.0,142.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/03btsm8"": ""Action/Adventure"", ""/m/06n90"":..."
20663735,Poovalli Induchoodan is sentenced for six yea...,Poovalli Induchoodan is sentenced for six yea...,/m/051zjwb,Narasimham,2000,NaN,175.0,"{""/m/0999q"": ""Malayalam Language""}","{""/m/03rk0"": ""India""}","{""/m/04t36"": ""Musical"", ""/m/02kdv5l"": ""Action""..."
2231378,"The Lemon Drop Kid , a New York City swindler,...","The Lemon Drop Kid , a New York City swindler,...",/m/06xtz3,The Lemon Drop Kid,1951-03-08,2300000.0,91.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/06qm3"": ""Screwball comedy"", ""/m/01z4y"": ""..."
595909,Seventh-day Adventist Church pastor Michael Ch...,Seventh-day Adventist Church pastor Michael Ch...,/m/02tqm5,A Cry in the Dark,1988-11-03,6908797.0,121.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America"", ""/m/...","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""D..."

In [144]:
df_movies_combined['m_wikipedia_id'] = df_movies_combined.index

In [146]:
df_movies_combined.head()

,m_plot_summary,cleaned_m_plot_summary,m_freebase_id,m_title,m_release_date,m_box_off_revenue,m_runtime,m_languages,m_countries,m_genres,m_wikipedia_id
m_wikipedia_id,,,,,,,,,,,
23890098,"Shlykov, a hard-working taxi driver and Lyosha...","Shlykov, a hard-working taxi driver and Lyosha...",/m/076w2lb,Taxi Blues,1990-09-07,NaN,110.0,"{""/m/06b_j"": ""Russian Language""}","{""/m/0f8l9c"": ""France"", ""/m/05vz3zq"": ""Soviet ...","{""/m/07s9rl0"": ""Drama"", ""/m/03q4nz"": ""World ci...",23890098
31186339,The nation of Panem consists of a wealthy Capi...,The nation of Panem consists of a wealthy Capi...,/m/0gkz15s,The Hunger Games,2012-03-12,686533290.0,142.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/03btsm8"": ""Action/Adventure"", ""/m/06n90"":...",31186339
20663735,Poovalli Induchoodan is sentenced for six yea...,Poovalli Induchoodan is sentenced for six yea...,/m/051zjwb,Narasimham,2000,NaN,175.0,"{""/m/0999q"": ""Malayalam Language""}","{""/m/03rk0"": ""India""}","{""/m/04t36"": ""Musical"", ""/m/02kdv5l"": ""Action""...",20663735
2231378,"The Lemon Drop Kid , a New York City swindler,...","The Lemon Drop Kid , a New York City swindler,...",/m/06xtz3,The Lemon Drop Kid,1951-03-08,2300000.0,91.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/06qm3"": ""Screwball comedy"", ""/m/01z4y"": ""...",2231378
595909,Seventh-day Adventist Church pastor Michael Ch...,Seventh-day Adventist Church pastor Michael Ch...,/m/02tqm5,A Cry in the Dark,1988-11-03,6908797.0,121.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America"", ""/m/...","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""D...",595909

In [145]:
write_file(df_movies_combined,'wiki_movie_summary.csv')